# Generated by Django 6.0.3 on 2026-03-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_contract_end_date_contract_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('RENT_REQUEST', 'Rent Request'), ('CONTRACT', 'Contract'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('SIGNED', 'Signed')], default='SENT', max_length=20),
        ),
    ]
