# Generated by Django 6.0.5 on 2026-05-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0004_alter_rentalrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='file',
        ),
        migrations.AddField(
            model_name='contract',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='terms',
            field=models.TextField(blank=True),
        ),
    ]
