# Generated by Django 6.0.5 on 2026-05-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0005_remove_contract_file_contract_rent_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
