# Generated by Django 6.0.5 on 2026-05-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0006_rentalrequest_end_date_rentalrequest_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='reviews_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
