# Generated by Django 6.0.5 on 2026-07-15 17:48

import django.db.models.deletion
import rentapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0007_property_rating_count_property_reviews_json_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='property',
            name='virtual_tour_url',
        ),
        migrations.CreateModel(
            name='Property360Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=rentapp.models.tour_image_upload_path)),
                ('is_initial_room', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rentapp.property')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pitch', models.FloatField(default=0.0)),
                ('yaw', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='rentapp.property360image')),
                ('target_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_hotspots', to='rentapp.property360image')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('source_room', 'target_room')},
            },
        ),
    ]
