# Generated by Django 6.0.5 on 2026-07-16 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0008_alter_rentalrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='unique_review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PropertyReviewVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_visited_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_visitors', to='rentapp.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-first_visited_at'],
                'unique_together': {('user', 'property')},
            },
        ),
    ]
