# Generated by Django 6.0.5 on 2026-07-20 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0009_property_unique_review_count_propertyreviewvisitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Occupied', 'Occupied')], default='Available', max_length=20),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_months', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reservation_time', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField()),
                ('reservation_status', models.CharField(choices=[('RESERVED', 'Reserved'), ('PENDING_PAYMENT', 'Pending Payment'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rentapp.property')),
            ],
            options={
                'ordering': ['-reservation_time'],
            },
        ),
    ]
