# Generated by Django 6.0.5 on 2026-07-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0010_property_status_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expiring_soon_notified',
            field=models.BooleanField(default=False),
        ),
    ]
