# Generated by Django 6.0.5 on 2026-07-20 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0011_reservation_expiring_soon_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('PAID', 'Paid'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='rentapp.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
